<?xml version="1.0"?>

<!-- TO-DO -->
<!-- change sizes -->
<!-- change inertia -->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="donatello">

    <xacro:include filename="donatello_include.urdf.xacro"/>
    <xacro:include filename="gazebo.xacro"/>

    <xacro:property name="pi" value="3.1415926"/>
    <xacro:property name="sqrt_2" value="1.41421356"/>

    <!-- SIZES -->

    <xacro:property name="prism_width" value="0.05"/>
 
    <xacro:property name="base_x" value="1.0"/>
    <xacro:property name="base_y" value="0.6"/>
    <xacro:property name="base_z" value="0.4"/>

    <xacro:property name="rear_cyl_l" value="0.05"/>
    <xacro:property name="rear_cyl_r" value="0.025"/>
    <xacro:property name="rear_width" value="0.6"/>

    <xacro:property name="axle_height" value="0.4"/>

    <xacro:property name="wheel_width" value="0.1"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    

    <!-- INERTIA -->


    <!-- LINKS -->

    <!-- soluciona el problema del root link con inercia en Gazebo-->
    <link name="dummy_link">
    </link>

    <link name="base_link"> 
        <visual>
            <geometry>
                <box size="${base_x} ${base_y} ${base_z}"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="${base_x} ${base_y} ${base_z}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="20.0"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.3" ixy="0.0" ixz="0.0" iyy="0.3" iyz="0.0" izz="0.3"/>
        </inertial>
    </link>

    
    <link name="rear_axle_link">
        <visual>
            <geometry>
                <cylinder length="${rear_cyl_l}" radius="${rear_cyl_r}"/>
            </geometry>
            <origin xyz="${-rear_cyl_l/2} 0 0" rpy="0 ${-pi/2} 0"/>
        </visual>
        <visual>
            <geometry>
                <box size="${prism_width} ${rear_width} ${prism_width}"/>
            </geometry>
            <origin xyz="${-rear_cyl_l-prism_width/2} 0 0" rpy="0 0 0"/>
        </visual>
        <visual>
            <geometry>
                <box size="${prism_width} ${prism_width} ${axle_height}"/>
            </geometry>
            <origin xyz="${-rear_cyl_l-prism_width/2} ${rear_width/2+prism_width/2} ${-axle_height/2+prism_width/2}" rpy="0 0 0"/>
        </visual>
        <visual>
            <geometry>
                <box size="${prism_width} ${prism_width} ${axle_height}"/>
            </geometry>
            <origin xyz="${-rear_cyl_l-prism_width/2} ${-(rear_width/2+prism_width/2)} ${-axle_height/2+prism_width/2}" rpy="0 0 0"/>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${rear_cyl_l}" radius="${rear_cyl_r}"/>
            </geometry>
            <origin xyz="${-rear_cyl_l/2} 0 0" rpy="0 ${-pi/2} 0"/>
        </collision>
        <collision>
            <geometry>
                <box size="${prism_width} ${rear_width} ${prism_width}"/>
            </geometry>
            <origin xyz="${-rear_cyl_l-prism_width/2} 0 0" rpy="0 0 0"/>
        </collision>
        <collision>
            <geometry>
                <box size="${prism_width} ${prism_width} ${axle_height}"/>
            </geometry>
            <origin xyz="${-rear_cyl_l-prism_width/2} ${rear_width/2+prism_width/2} ${-axle_height/2+prism_width/2}" rpy="0 0 0"/>
        </collision>
        <collision>
            <geometry>
                <box size="${prism_width} ${prism_width} ${axle_height}"/>
            </geometry>
            <origin xyz="${-rear_cyl_l-prism_width/2} ${-(rear_width/2+prism_width/2)} ${-axle_height/2+prism_width/2}" rpy="0 0 0"/>
        </collision>

        <inertial>
            <mass value="1.0"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.083" ixy="0.0" ixz="0.0" iyy="0.021" iyz="0.0" izz="0.1"/>
        </inertial>

    </link>


    <link name="front_left_axle_link">
        <visual>
            <geometry>
                <box size="${prism_width} ${prism_width} ${sqrt_2*base_z}"/>
            </geometry>
            <origin xyz="${-axle_height/2} 0 ${-axle_height/2}" rpy="0 ${pi/4} 0"/>
        </visual>
        <visual>
            <geometry>
                <box size="${prism_width} ${prism_width} ${sqrt_2*base_z}"/>
            </geometry>
            <origin xyz="${axle_height/2} 0 ${-axle_height/2}" rpy="0 ${-pi/4} 0"/>
        </visual>

        <collision>
            <geometry>
                <box size="${prism_width} ${prism_width} ${sqrt_2*base_z}"/>
            </geometry>
            <origin xyz="${-axle_height/2} 0 ${-axle_height/2}" rpy="0 ${pi/4} 0"/>
        </collision>
        <collision>
            <geometry>
                <box size="${prism_width} ${prism_width} ${sqrt_2*base_z}"/>
            </geometry>
            <origin xyz="${axle_height/2} 0 ${-axle_height/2}" rpy="0 ${-pi/4} 0"/>
        </collision>

        <inertial>
            <mass value="1.0"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.083" ixy="0.0" ixz="0.0" iyy="0.021" iyz="0.0" izz="0.1"/>
        </inertial>
    </link>

    <link name="front_right_axle_link">
        <visual>
            <geometry>
                <box size="${prism_width} ${prism_width} ${sqrt_2*base_z}"/>
            </geometry>
            <origin xyz="${-axle_height/2} 0 ${-axle_height/2}" rpy="0 ${pi/4} 0"/>
        </visual>
        <visual>
            <geometry>
                <box size="${prism_width} ${prism_width} ${sqrt_2*base_z}"/>
            </geometry>
            <origin xyz="${axle_height/2} 0 ${-axle_height/2}" rpy="0 ${-pi/4} 0"/>
        </visual>

        <collision>
            <geometry>
                <box size="${prism_width} ${prism_width} ${sqrt_2*base_z}"/>
            </geometry>
            <origin xyz="${-axle_height/2} 0 ${-axle_height/2}" rpy="0 ${pi/4} 0"/>
        </collision>
        <collision>
            <geometry>
                <box size="${prism_width} ${prism_width} ${sqrt_2*base_z}"/>
            </geometry>
            <origin xyz="${axle_height/2} 0 ${-axle_height/2}" rpy="0 ${-pi/4} 0"/>
        </collision>

        <inertial>
            <mass value="1.0"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.083" ixy="0.0" ixz="0.0" iyy="0.021" iyz="0.0" izz="0.1"/>
        </inertial>
    </link>
 
    
    <!-- JOINTS -->

    <joint name="dummy_joint" type="fixed">
        <parent link="dummy_link"/>
        <child link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    
    <!--
    <joint name="rear_axle_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_axle_link"/>
        <origin xyz="${-base_x/2} 0 -0.15" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
    </joint>

    <joint name="front_left_axle_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_left_axle_link"/>
        <origin xyz="0.3 ${0.3+prism_width/2} -0.15" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="front_right_axle_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_right_axle_link"/>
        <origin xyz="0.3 ${-(0.3+prism_width/2)} -0.15" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>
    -->

    <joint name="rear_axle_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_axle_link"/>
        <origin xyz="${-base_x/2} 0 -0.15" rpy="0 0 0"/>
    </joint>

    <joint name="front_left_axle_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_left_axle_link"/>
        <origin xyz="0.3 ${0.3+prism_width/2} -0.15" rpy="0 0 0"/>
    </joint>

    <joint name="front_right_axle_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_right_axle_link"/>
        <origin xyz="0.3 ${-(0.3+prism_width/2)} -0.15" rpy="0 0 0"/>
    </joint>
    

    <xacro:wheel prefix="back_left_wheel" parent="rear_axle_link" x="${-rear_cyl_l-prism_width/2}" y="${rear_width/2+prism_width+0.1/2}" z="${-axle_height}" width="${wheel_width}" radius="${wheel_radius}" roll="${-pi/2}"/>
    <xacro:wheel prefix="back_right_wheel" parent="rear_axle_link" x="${-rear_cyl_l-prism_width/2}" y="${-(rear_width/2+prism_width+0.1/2)}" z="${-axle_height}" width="${wheel_width}" radius="${wheel_radius}" roll="${-pi/2}"/>

    <xacro:wheel prefix="center_left_wheel" parent="front_left_axle_link" x="${-axle_height}" y="${prism_width/2+0.1/2}" z="${-axle_height}" width="${wheel_width}" radius="${wheel_radius}" roll="${-pi/2}"/>
    <xacro:wheel prefix="center_right_wheel" parent="front_right_axle_link" x="${-axle_height}" y="${-(prism_width/2+0.1/2)}" z="${-axle_height}" width="${wheel_width}" radius="${wheel_radius}" roll="${-pi/2}"/>

    <xacro:wheel prefix="front_left_wheel" parent="front_left_axle_link" x="${axle_height}" y="${prism_width/2+0.1/2}" z="${-axle_height}" width="${wheel_width}" radius="${wheel_radius}" roll="${-pi/2}"/>
    <xacro:wheel prefix="front_right_wheel" parent="front_right_axle_link" x="${axle_height}" y="${-(prism_width/2+0.1/2)}" z="${-axle_height}" width="${wheel_width}" radius="${wheel_radius}" roll="${-pi/2}"/>



</robot>
