#gazebo_ros_control:
#  pid_gains:
#    back_left_wheel_joint:
#      p: 100.0
#      i: 0.01
#      d: 0.1
#    back_right_wheel_joint:
#      p: 100.0
#      i: 0.01
#      d: 0.1
#    center_left_wheel_joint:
#      p: 100.0
#      i: 0.01
#      d: 0.1
#    center_right_wheel_joint:
#      p: 100.0
#      i: 0.01
#      d: 0.1
#    front_left_wheel_joint:
#      p: 100.0
#      i: 0.01
#      d: 0.1
#    front_right_wheel_joint:
#      p: 100.0
#      i: 0.01
#      d: 0.1
          
diff_drive_controller:

  type: "diff_drive_controller/DiffDriveController"

  publish_rate: 50.0

  base_frame_id: "base_link"

  left_wheel: ["back_left_wheel_joint","center_left_wheel_joint","front_left_wheel_joint"]
  right_wheel: ["back_right_wheel_joint","center_right_wheel_joint","front_right_wheel_joint"]

  #left_wheel: ["back_left_wheel_joint"]
  #right_wheel: ["back_right_wheel_joint"]

  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  wheel_separation: 0.7
  wheel_radius: 0.1

  use_stamped_vel: false